/** NEW: Prepared editable content, not prose generated by JEV. Never invent customers,
 * testimonials, reviews, statistics or prices. Draft flags survive composition and export. */
import { SCHEMA_VERSION, DEFAULT_BLOCKS, DEFAULT_THEME } from './catalog.mjs';
import { DEFAULT_PRESENTATION } from './design.mjs';
import { DEFAULT_ELEMENTS } from './elements.mjs';
import { DEFAULT_INTERFACE, isInterfaceBlock, preparedInterface } from './interfaces.mjs';
export function newItemId() { return `item-${globalThis.crypto.randomUUID()}`; }
const item = (title, body = '', meta = '', price = '') => ({ id: newItemId(), removedParts: [], title, body, meta, price, image: '', alt: '', imageSize: { width: 100, height: null, fit: 'cover' }, href: '', icon: 'default', buttonIcon: 'default', uiType: 'default', placements: { iconPlacement: 'default', textOrder: 'default', buttonIconPlacement: 'default' } });
export function makeInterfaceSection(block, family = 'application') {
  const content = preparedInterface(block);
  return { removedParts: [], id: 'hero', group: 'hero', block, eyebrow: '', title: '', body: '', button: '', href: '', image: '', alt: '', imageSize: { width: 100, height: null, fit: 'cover' }, locked: false, draft: true, presentation: { ...DEFAULT_PRESENTATION }, elements: { ...DEFAULT_ELEMENTS }, interface: { ...DEFAULT_INTERFACE }, featuredItemId: null, ...content, items: content.items.map((entry, index) => ({ ...item(entry.title, entry.body, entry.meta, entry.price), ...entry, art: index, imageSize: { width: 100, height: null, fit: 'cover' } })) };
}
export function makeSection(group, block = DEFAULT_BLOCKS[group], family = 'studio') {
  if (group === 'hero' && isInterfaceBlock(block)) return makeInterfaceSection(block, family);
  const result = { removedParts: [], id: group, group, block, eyebrow: '', title: '', body: '', button: '', href: '', image: '', alt: '', imageSize: { width: 100, height: null, fit: 'cover' }, items: [], locked: false, draft: true, presentation: { ...DEFAULT_PRESENTATION }, elements: { ...DEFAULT_ELEMENTS }, interface: { ...DEFAULT_INTERFACE } };
  const content = {
    navigation: { title: 'Navigation' },
    hero: { eyebrow: 'A considered approach', title: 'Good things begin with a clear idea.', body: 'Introduce what you do, who you do it for, and what makes your approach different.', button: 'Explore more', href: '#contact' },
    features: { eyebrow: 'The essentials', title: 'Thoughtfully made. Simply useful.', body: 'Make your most important benefits clear at a glance.', items: [item('A clear starting point', 'Describe the first meaningful benefit for your visitors.'), item('Built around you', 'Explain how your offering fits the people you serve.'), item('Every detail matters', 'Share one concrete difference in your approach.')] },
    about: { eyebrow: 'Our story', title: 'A little about what drives us.', body: 'Tell your story in your own words. Describe your purpose, the people behind the work, and what visitors can expect.' },
    services: { eyebrow: 'What we do', title: 'The right support, at every step.', body: 'Replace these examples with your actual services or offerings.', items: [item('Discovery', 'Understand the goal and explore the possibilities.'), item('Design', 'Turn a clear direction into something tangible.'), item('Delivery', 'Bring the details together and plan what comes next.')] },
    gallery: { eyebrow: 'Selected work', title: 'A few things worth a closer look.', body: 'Add your own images, project names and descriptions.', items: [item('Project one', 'Replace with a description of your work.', 'Project / 01'), item('Project two', 'Replace with a description of your work.', 'Project / 02'), item('Project three', 'Replace with a description of your work.', 'Project / 03')] },
    process: { eyebrow: 'How it works', title: 'From first thought to next chapter.', body: '', items: [item('Start a conversation', 'Share what you have in mind and what matters most.'), item('Find the direction', 'Explore the options and agree on a clear approach.'), item('Make it happen', 'Bring the plan to life, one thoughtful step at a time.')] },
    pricing: { eyebrow: 'Your options', title: 'Find the right starting point.', body: 'Add your actual prices and plan details before publishing.', items: [item('Essential', 'Add included features, one per line.', 'per project', 'Ask for a quote'), item('Complete', 'Add included features, one per line.', 'per project', 'Ask for a quote'), item('Custom', 'Describe a tailored option.', 'tailored to you', 'Let’s talk')] },
    faq: { eyebrow: 'Good questions', title: 'A little more clarity.', body: 'Replace these with real answers for your visitors.', items: [item('How do we get started?', 'Describe the first step a new customer should take.'), item('What is included?', 'Explain exactly what your offering includes and any limitations.'), item('How can I ask another question?', 'Add your preferred contact method and response expectations.')] },
    contact: { eyebrow: 'Say hello', title: 'Let’s make something good.', body: 'Tell visitors how to reach you. Add a real public contact email in the Brand settings.', button: 'Prepare email', href: '' },
    cta: { eyebrow: 'The next step', title: 'Ready for a fresh perspective?', body: 'Give your visitors one clear next step.', button: 'Get in touch', href: '#contact' },
    footer: { title: 'Made with intention.', body: 'Add a short closing thought or your business details.' }
  };
  Object.assign(result, content[group]);
  if (group === 'hero') {
    const headlines = { saas: 'Less friction. More possibility.', studio: 'Good ideas deserve a thoughtful home.', portfolio: 'Selected work. A singular perspective.', local: 'Something good, right around the corner.', wellness: 'Make a little more room for yourself.', hospitality: 'A place to slow down and stay a while.', event: 'A new perspective starts here.', general: 'A clearer way to tell your story.' };
    result.title = headlines[family] || headlines.general;
  }
  if (family === 'hospitality' && group === 'gallery') { result.eyebrow = 'Take a look around'; result.title = 'Space to settle in.'; result.items = [item('Your space', 'Add a real photo and description.', 'The stay'), item('The details', 'Add a real photo and description.', 'Inside'), item('Around us', 'Add a real photo and description.', 'The setting')]; }
  result.items.forEach((entry, index) => { entry.art = index; });
  result.featuredItemId = group === 'pricing' && block === 'pricing-featured' ? result.items[1]?.id ?? null : null;
  return result;
}
export function createSpec(brandName = 'Studio North') {
  return { schemaVersion: SCHEMA_VERSION, name: `${brandName} website`, family: 'studio', brief: '', brand: { name: brandName, tagline: 'Thoughtful ideas, made tangible.', email: '', cta: 'Let’s talk', href: '#contact', language: 'en' }, theme: { ...DEFAULT_THEME, font: 'editorial' }, sections: ['navigation', 'hero', 'features', 'gallery', 'services', 'process', 'faq', 'contact', 'footer'].map((group) => makeSection(group)), pages: [] };
}
export function isBareLiteralPrefix(prefix) {
  // A bare field starts a sentence/line or follows a preceding quoted literal.
  // Qualified forms such as “hero button:” belong to the element-copy router.
  return /(?:^|[\n;.!?,"”])\s*(?:brand|headline|tagline|button)\s*:\s*$/iu.test(prefix);
}
export function extractLiteralFields(prompt) {
  // NEW: Deliberately bounded literal extraction, not an invented text-generation step.
  // Supported syntax: Brand: "Acme"; Headline: "Exact copy"; Tagline: "..."; Button: "...".
  const result = {};
  for (const [key, pattern] of Object.entries({ name: /\bbrand\s*:\s*["“]([^"”\n]{1,100})["”]/iu, headline: /\bheadline\s*:\s*["“]([^"”\n]{1,300})["”]/iu, tagline: /\btagline\s*:\s*["“]([^"”\n]{1,250})["”]/iu, cta: /\bbutton\s*:\s*["“]([^"”\n]{1,100})["”]/iu })) {
    for (const match of prompt.matchAll(new RegExp(pattern.source, `${pattern.flags}g`))) {
      const quoteOffset = match.index + match[0].search(/["“]/u);
      if (isBareLiteralPrefix(prompt.slice(0, quoteOffset))) { result[key] = match[1]; break; }
    }
  }
  return result;
}
