# NEW: Optional end-to-end editor workflow tests. Requires Python Playwright.
import sys, os, json, io, zipfile, urllib.request, struct, zlib
from pathlib import Path
import browser_harness as h
ARTIFACTS = Path(os.environ.get('FORMA_TEST_ARTIFACTS', str(h.ROOT / 'artifacts')))
ARTIFACTS.mkdir(parents=True, exist_ok=True)
BROWSER_PATH = os.environ.get('FORMA_TEST_BROWSER')

from playwright.sync_api import sync_playwright, expect
results=[]
def ok(name, condition=True):
    if not condition: raise AssertionError(name)
    results.append(name); print('PASS',name,flush=True)
def frame(page): return page.frame_locator('#preview-frame')
def spec(page):
    before=page.evaluate('window.__downloads.length')
    page.locator('#download-json-button').click()
    page.wait_for_function('(n) => window.__downloads.length>n',arg=before)
    last=page.evaluate('window.__downloads.at(-1)')
    return json.loads(bytes(last['bytes']))
def pause(page): page.wait_for_timeout(550)
def click_preview(page, locator):
    # Playwright's element bounding box does not apply the iframe CSS scale.
    # Use the actual rendered coordinates, just as a user pointer would.
    locator.evaluate('(el)=>el.scrollIntoView({block:"center",inline:"nearest"})')
    rect=locator.evaluate('(el)=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}}')
    outer=page.locator('#preview-frame').bounding_box()
    scale=outer['width']/page.locator('#preview-frame').evaluate('(el)=>el.clientWidth')
    page.mouse.click(outer['x']+(rect['x']+rect['w']/2)*scale,outer['y']+(rect['y']+rect['h']/2)*scale)


with sync_playwright() as p:
    b=p.chromium.launch(**({'executable_path': BROWSER_PATH} if BROWSER_PATH else {}),headless=True)
    page=b.new_page(viewport={'width':1600,'height':1000},device_scale_factor=1)
    page.set_default_timeout(7000)
    errors=[]
    page.on('pageerror',lambda e: errors.append(str(e)))
    page.on('console',lambda m: errors.append(m.text) if m.type=='error' else None)
    page.on('dialog',lambda d: d.accept())
    h.load(page)
    expect(frame(page).locator('h1')).to_have_text('Good ideas deserve a thoughtful home.')
    ok('Initial example renders without an API call')
    ok('Both design/provider selectors have usable widths',page.locator('#provider-mode').bounding_box()['width']>90)
    expect(frame(page).locator('body')).to_have_attribute('data-edit-mode','true')
    ok('Sandbox preview runtime passes its CSP and exchanges channel messages')
    page.locator('#build-button').click()
    expect(page.locator('#settings-dialog')).to_be_visible()
    ok('Live mode requires a key instead of silently using demo')
    page.locator('[data-close="settings-dialog"]').first.click()
    page.locator('#provider-mode').select_option('demo')
    page.locator('#prompt').fill('Brand: "Orbit" Headline: "Make room for focus." A dark SaaS website with bento features, pricing, FAQ and contact. No animation.')
    page.locator('#build-button').click()
    expect(frame(page).locator('h1')).to_have_text('Make room for focus.')
    expect(page.locator('#build-button')).to_be_enabled()
    pause(page)
    s=spec(page)
    ok('Offline composition produces a saved dark SaaS design',s['theme']['palette']=='midnight' and s['brand']['name']=='Orbit' and any(x['group']=='pricing' for x in s['sections']))
    page.locator('[data-inspector-tab="decisions"]').click()
    expect(page.locator('#inspector-content')).to_contain_text('Local demo rules (not JEV)')
    ok('Decision report clearly distinguishes offline rules from JEV')
    page.locator('[data-inspector-tab="design"]').click()
    page.locator('[data-palette="sage"]').click();pause(page)
    expect(frame(page).locator('.site')).to_have_class(__import__('re').compile('palette-sage'))
    page.locator('#undo-button').click();pause(page)
    expect(frame(page).locator('.site')).to_have_class(__import__('re').compile('palette-midnight'))
    page.locator('#redo-button').click();pause(page)
    expect(frame(page).locator('.site')).to_have_class(__import__('re').compile('palette-sage'))
    ok('Manual theme editing, undo and redo update the actual preview')
    page.locator('[data-lock-setting="palette"]').click()
    page.locator('#prompt').fill('Make it dark, but preserve the rest. No animation.')
    page.locator('#build-button').click();expect(page.locator('#build-button')).to_be_enabled();pause(page)
    ok('A locked palette survives a contradictory design request',spec(page)['theme']['palette']=='sage')
    click_preview(page, frame(page).locator('h1'))
    expect(page.get_by_label('Heading',exact=True)).to_be_visible()
    ok('Clicking the preview opens the selected section editor')
    page.get_by_label('Heading',exact=True).fill('A calmer place to do your best work.')
    page.get_by_label('Public contact email',exact=True).fill('hello@example.com')
    page.get_by_label('Public contact email',exact=True).blur()
    pause(page)
    expect(frame(page).locator('h1')).to_have_text('A calmer place to do your best work.')
    ok('Literal copy edits and contact settings reach the rendered site')
    # NEW: A small standards-valid raster fixture exercises local image decoding.
    def png_chunk(kind, data):
        return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data) & 0xffffffff)
    raster = ARTIFACTS / 'fixture.png'
    raster.write_bytes(b'\x89PNG\r\n\x1a\n' + png_chunk(b'IHDR', struct.pack('>IIBBBBB', 32, 32, 8, 2, 0, 0, 0)) + png_chunk(b'IDAT', zlib.compress((b'\x00' + bytes([92, 128, 77]) * 32) * 32)) + png_chunk(b'IEND', b''))
    page.locator('input[data-image-path]').first.set_input_files(str(raster));pause(page)
    expect(frame(page).locator('.hero-visual img')).to_be_visible()
    image_spec = spec(page)
    ok('Raster image upload is decoded locally and embedded as WebP',next(x for x in image_spec['sections'] if x['group']=='hero')['image'].startswith('data:image/webp;base64,'))
    page.locator('[data-clear-image]').first.click();pause(page)
    page.locator('#save-button').click();pause(page)
    page.locator('[data-inspector-tab="design"]').click()
    ok('Manual checkpoints are listed',page.locator('[data-restore-history]').count()>=1)
    page.locator('[data-select-section="hero"]').click()
    page.locator('[data-inspector-tab="content"]').click()
    page.get_by_label('Heading',exact=True).fill('A temporary change to restore.')
    page.wait_for_timeout(1800)
    page.locator('[data-inspector-tab="design"]').click()
    page.locator('[data-restore-history]').first.click();pause(page)
    expect(frame(page).locator('h1')).to_have_text('A calmer place to do your best work.')
    ok('Checkpoint restore recovers the saved content')
    page.locator('[data-left-tab="library"]').click()
    page.locator('#library-search').fill('gallery')
    page.locator('[data-add-block="gallery-grid"]').click();pause(page)
    ok('Free component library adds a gallery section',any(x['group']=='gallery' for x in spec(page)['sections']))
    page.locator('[data-inspector-tab="design"]').click()
    page.locator('[data-lock-section="gallery"]').click()
    page.locator('[data-left-tab="brief"]').click()
    page.locator('#prompt').fill('Remove the gallery and FAQ. Keep everything else.')
    page.locator('#build-button').click();expect(page.locator('#build-button')).to_be_enabled();pause(page)
    s=spec(page)
    ok('Section locks are enforced while other requested sections can be removed',any(x['group']=='gallery' for x in s['sections']) and not any(x['group']=='faq' for x in s['sections']))
    # Add FAQ back for interaction checks.
    page.locator('[data-left-tab="library"]').click();page.locator('#library-search').fill('')
    page.locator('[data-add-block="faq-accordion"]').click();pause(page)
    page.locator('#inspect-button').click()
    faq=frame(page).locator('.faq-item').first
    click_preview(page, faq.locator('summary'))
    expect(faq).to_have_attribute('open','')
    ok('FAQ expands in interaction mode rather than selecting a section')
    page.locator('[data-device="mobile"]').click();pause(page)
    expect(frame(page).locator('.mobile-nav')).to_be_visible()
    click_preview(page, frame(page).locator('.mobile-nav summary'))
    expect(frame(page).locator('.mobile-nav')).to_have_attribute('open','')
    click_preview(page, frame(page).locator('.mobile-nav nav a').first)
    ok('Mobile navigation opens and closes after an internal link',frame(page).locator('.mobile-nav').get_attribute('open') is None)
    overflow=frame(page).locator('html').evaluate('(el)=>({width:el.clientWidth,scroll:el.scrollWidth})')
    ok('390px generated site has no horizontal overflow',overflow['scroll']<=overflow['width']+1)
    page.locator('[data-device="desktop"]').click();pause(page)
    page.locator('#canvas-code-tab').click()
    expect(page.locator('#source-code')).to_contain_text('A calmer place to do your best work.')
    ok('HTML inspector contains rendered source, not a screenshot')
    page.locator('#canvas-preview-tab').click()
    page.locator('#export-button').click();expect(page.locator('#export-dialog')).to_be_visible()
    expect(page.locator('#export-review')).to_contain_text('draft')
    ok('Export preflight warns about unreviewed prepared copy')
    before=page.evaluate('window.__downloads.length')
    page.locator('#export-confirm').click()
    page.wait_for_function('(n)=>window.__downloads.length>n',arg=before)
    output=page.evaluate('window.__downloads.at(-1)')
    archive=zipfile.ZipFile(io.BytesIO(bytes(output['bytes'])))
    ok('Export downloads a valid ZIP with a standalone site and license',archive.testzip() is None and 'index.html' in archive.namelist() and 'licenses/HYPERUI.txt' in archive.namelist())
    ok('Export preserves literal copy',b'A calmer place to do your best work.' in archive.read('index.html'))
    page.locator('#save-button').click();pause(page)
    page.locator('#projects-button').click();expect(page.locator('#project-list')).to_contain_text('Orbit')
    original_id=page.locator('[data-open-project]').first.get_attribute('data-open-project')
    page.locator('#modal-new-button').click();pause(page)
    expect(frame(page).locator('.wordmark').first).to_contain_text('Your brand')
    ok('New project starts a separate canvas')
    page.locator('#projects-button').click()
    page.locator('[data-open-project="'+original_id+'"]').click();pause(page)
    expect(frame(page).locator('h1')).to_have_text('A calmer place to do your best work.')
    ok('Saved projects restore content and design')
    imported = ARTIFACTS / 'roundtrip.project.json'
    imported.write_text(json.dumps(spec(page)), encoding='utf8')
    page.locator('#projects-button').click()
    page.locator('#import-file').set_input_files(str(imported));pause(page)
    expect(frame(page).locator('h1')).to_have_text('A calmer place to do your best work.')
    ok('Project JSON imports into a new editable local project')
    # Mobile editor navigation is separate from viewport controls.
    page.set_viewport_size({'width':390,'height':844});pause(page)
    page.locator('.mobile-workspace-nav [data-panel="inspector"]').click();pause(page)
    expect(page.locator('.inspector-panel')).to_be_visible()
    page.locator('.mobile-workspace-nav [data-panel="canvas"]').click();pause(page)
    page.locator('[data-device="mobile"]').click();pause(page)
    page.screenshot(path=str(ARTIFACTS/'forma-mobile.png'),full_page=True)
    ok('Mobile editor has working panel navigation',page.locator('html').evaluate('(el)=>el.scrollWidth<=el.clientWidth+1'))
    # Screenshots are actual rendered local-rule output.
    page.set_viewport_size({'width':1600,'height':1000});pause(page)
    page.locator('[data-device="desktop"]').click()
    page.locator('[data-inspector-tab="design"]').click();page.locator('[data-left-tab="brief"]').click()
    page.locator('#prompt').fill('Try another direction, or refine this site.')
    pause(page)
    frame(page).locator('html').evaluate('(el)=>window.scrollTo(0,0)')
    page.locator('#inspector-content').evaluate('(el)=>el.scrollTop=0')
    page.locator('#brief-content').evaluate('(el)=>el.scrollTop=0')
    page.locator('#prompt').blur()
    page.screenshot(path=str(ARTIFACTS/'forma-workspace.png'),full_page=True)
    ok('No browser JavaScript or CSP errors occurred',not errors)
    (ARTIFACTS/'browser-results.json').write_text(json.dumps({'checks':results,'errors':errors,'transport':'Local HTTP binding (managed-browser mode)' if os.environ.get('FORMA_BROWSER_HTTP_BRIDGE') == '1' else 'Native browser HTTP'},indent=2))
    b.close()
    print('BROWSER CHECKS:',len(results),flush=True)
